---
title: "Model 4 Simulation"
author: "Dongyue Xie"
date: YYYY-MM-DD
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->

# Situation 1
In this simulation, the correlation between ${x}$ and ${y}$ is induced by two orthogonal directions.
```{r,warning=FALSE,message=FALSE}
library(scca)

sigma_x = arcov(0.7,100)
sigma_y=sigma_x

edges=c(as.numeric(combn(1:10,2)),as.numeric(combn(11:20,2)),21:100)

#u=c(rep(1,10),rep(-1,10),rep(0,80))
u=c(rep(c(1,0.2),10),rep(0,80))
v=c(rep(c(1,1,0.2,0.2,0.2),4),rep(0,80))
model4S0s1=finals(s0cca_simu(100,u,v,50,'normal_oth',1,sigma_x,sigma_y))
model4S1s1=finals(s1cca_simu(100,u,v,50,'normal_oth',1,sigma_x,sigma_y))
model4elnets1=finals(elnet.cca.simu(100,u,v,50,'normal_oth',1,sigma_x,sigma_y))
model4gsccas1=finals(gscca.simu.normal(100,edges,edges,u,v,50,'normal_oth',1,sigma_x,sigma_y,gamma.u = 2.12,gamma.v = 2.12))
```

```{r}
model4S0s1
model4S1s1
model4elnets1
model4gsccas1
```

# Situation 2
```{r,warning=FALSE,message=FALSE}
#situation 2
u=c(rep(c(0.5,-0.5),10),rep(0,80))
v=u
model4S0s2=finals(s0cca_simu(100,u,v,50,'normal_mis',1,sigma_x,sigma_y))
model4S1s2=finals(s1cca_simu(100,u,v,50,'normal_mis',1,sigma_x,sigma_y))
model4elnets2=finals(elnet.cca.simu(100,u,v,50,'normal_mis',1,sigma_x,sigma_y))
model4gsccas2=finals(gscca.simu.normal(100,edges,edges,u,v,50,'normal_mis',1,sigma_x,sigma_y,plain = F))
```

```{r}
model4S0s2
model4S1s2
model4elnets2
model4gsccas2
```
## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
